### ISSUE TITLE
Fasta file format IO

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#10]
**Describe the solution you'd like**
I'd like a fasta parser than parses fasta into an AnnotatedSequence struct or set of AnnotatedSequence structs. Most of the struct can be blank but the AnnotatedSequence.Sequence.Sequence should be a single string of characters with no whitespace and AnnotatedSequence.Sequence.Description should be the description. This is a really great first contribution and there's no rush to implement so I thought it'd be great to share here!

**Additional context**
Here's a [spec](https://en.wikipedia.org/wiki/FASTA_format) from wikipedia. The resulting parser should be placed in [io.go](https://github.com/TimothyStiles/poly/blob/prime/io.go) along with tests in [io_test.go](https://github.com/TimothyStiles/poly/blob/prime/io_test.go). More information on the AnnotatedSequence struct can also be found in [io.go](https://github.com/TimothyStiles/poly/blob/prime/io.go).

**Comment by 0x106** [comment]
@TimothyStiles I'd be happy to work on this feature if you'd like?

**Comment by TimothyStiles** [comment]
@0x106 go for it! Is there anything I can help with?

**Comment by 0x106** [comment]
I should be fine to get started thanks. I had a look through io.go as a starting point and am going to set up a bunch of test cases before I actually write anything.

**Comment by 0x106** [comment]
Hey I pushed an initial version. It reads sequences from a .fasta file into an array of AnnotatedSequence structs (header line gets written into `Sequence.Description` and sequence into `Sequence.Sequence`.

This was my first time writing anything in Go so you might want to give it a quick check to make sure it's idiomatic / actually correct.

**Comment by TimothyStiles** [comment]
Thanks to @0x106 for adding this in PR #37! There still needs to be a build fasta function but we can merge before adding that.
