### ISSUE TITLE
Uniprot parser

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#100]
**Is your feature request related to a problem? Please describe.**
A parser for Uniprot XML data dumps (https://www.uniprot.org/downloads)

**Describe the solution you'd like**
A way to digest all of the Uniprot data dumps.

**Describe alternatives you've considered**
We built the concurrent Fasta parser to handle the Uniprot FASTA dumps, but a lot of information is lost there. It would be greatly preferred to have the XML parsed, so we can get full documentation of every protein.

**Additional context**

**Comment by jkhales** [comment]
> We built the concurrent Fasta parser to handle the Uniprot FASTA dumps, but a lot of information is lost there. 

Why is there data loss with FASTA, but now with XML?

**Comment by Koeng101** [comment]
FASTA only contains sequence data and name, no metadata. The XML dumps have pretty much everything.
