### ISSUE TITLE
Enable Biologist Contribution

### ISSUE THREAD

**Issue by rkrishnasanka** [TimothyStiles/poly#104]
**Is your feature request related to a problem? Please describe.**
Enable a clear path for biologists to contribute to poly -
1. Biologists should do a PR to show that they’ve contributed to a GitHub repo.
2. Should be able to contribute input and output examples/test data that’s real-world (and academically citable)
3. Capture OCRID of bio/academic contributors
4. Zenodo DOI should be linked to contributions

**Describe the solution you'd like**
`contributor-log` file where we have individual contributor log entries (this should be the job of the bio-maintainer) 

`contributors` folder with individual markdown files where users can add -
1. Proposed Workflows
2. Academic references
3. TBD

**Describe alternatives you've considered**
None yet

**Additional context**
I think this would help enable us to capture the contributions of non-software folks and help us better build poly as a community-driven tool. This will also force us to have some type of "Truth" / "Specification" to build the software against.

**Comment by TimothyStiles** [comment]
I'll expand more on this soon but we should also think about writing a github action bot that tries to contact both contributors and reviewers and have special reviewer cred somewhere in publication. Helps incentivize third-party reviewers.

**Comment by TimothyStiles** [comment]
We should also have a getting started with markdown / markdown style guide. We already have a bot that lints markdown.

**Comment by rkrishnasanka** [comment]
> I'll expand more on this soon but we should also think about writing a github action bot that tries to contact both contributors and reviewers and have special reviewer cred somewhere in publication. Helps incentivize third-party reviewers.

I think that's an excellent idea. Having 3rd party reviews and people being able to run conversations on GitHub would definitely make this better.

**Comment by TimothyStiles** [comment]
Closing for now but feel free to open this back up.
