### ISSUE TITLE
Standard VScode and GH codespace setup.

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#117]
**Is your feature request related to a problem? Please describe.**
I believe VScode and Github codespaces allow you to share settings and plugins within `.vscode` directory

**Describe the solution you'd like**
I should collect the tools that I use personally and include them as part of repo settings in `.vscode`.

**Comment by rkrishnasanka** [comment]
What all do you need working on this? I've been playing around with this for my tools which are far more complex in terms of dependency chains, I can probably get a draft of this done this weekend.

**Comment by TimothyStiles** [comment]
@rkrishnasanka At the very minimum something that includes the Go extension published by microsoft with code coverage highlighting turned on. I've also been experimenting the official vision studio liveshare extension which could be of use but I still don't really know how it works in full.

**Comment by TimothyStiles** [comment]
Now that I'm thinking of it perhaps the official github and github code extensions would be nice but probably not necessary to include? I'd also be curious to hear what other people are using for extensions.

**Comment by rkrishnasanka** [comment]
> @rkrishnasanka At the very minimum something that includes the Go extension published by microsoft with code coverage highlighting turned on. I've also been experimenting the official vision studio live share extension which could be of use but I still don't really know how it works in full.

Basically, they create a docker image with the code folder mounted, vscode installed. It then uses the remote dev features (which are really good) to connect to the docker image and runs stuff.

**Comment by TimothyStiles** [comment]
Closing as this has been solved as of #171.
