### ISSUE TITLE
BtgZI fasta fails parsing

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#126]
**Describe the bug**
http://rebase.neb.com/cgi-bin/seqsget?BtgZI.NEBC8843.pro parses using the build in parser, but spaces are not removed. We should remove all spaces in the fasta parsers.

**To Reproduce**
Download the linked fasta file and parse it using poly.

**Expected behavior**
A fasta file's sequence should have no spaces.

**Comment by TimothyStiles** [comment]
@Koeng101 can I close this issue or has this not been solved yet?

**Comment by Koeng101** [comment]
This is **NOT FIXED**. If someone asks for something to PR to get started, this is it.

**Comment by ThomVett** [comment]
A clarifying question about this, what do you mean by parse it using `poly`? Using one of the cli entrypoints or from inside the code? Should this be added as a unit test?
