### ISSUE TITLE
Enhanced poly ha output

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#14]
**Is your feature request related to a problem? Please describe.**
The most likely use of hash outputs is going to be linking hash IDs to the LOCUS of a Genbank file, since that is typically the unique identifier. There should be a non-default option for the hash function to output the LOCUS of the Genbank file it has parsed.

**Describe the solution you'd like**
I would like the poly hash function to have 1 new optional option:
1. --locus (outputs locus)

**Describe alternatives you've considered**
I've considered just getting this information from the json file, but that seemed overly complicated for systems that already have nice genbank output.

**Additional context**

**Comment by TimothyStiles** [comment]
This seems like one that's easy enough. I'm not really sure what you want to output to look like here. Think you could make a pull request for this @Koeng101?

**Comment by Koeng101** [comment]
Will do.

**Comment by Koeng101** [comment]
https://timothystiles.github.io/polydocs/docs/cli-hashing

`cat bsub.gbk | poly ha -i gbk -o json | jq -r '.Meta.Accession,.Sequence.Hash'`

Has the functionality I was looking for.

**Comment by TimothyStiles** [comment]
@Koeng101 this functionality was also partially added as of last night.

https://timothystiles.github.io/poly/docs/cli-hashing/#hashing-with-a-system-call

Still needs the locus if that's what you're going for but what you have seems like a good idiomatic solution for bash.
