### ISSUE TITLE
Ability to calculate melting temperature for non-default concentrations

### ISSUE THREAD

**Issue by rkrishnasanka** [TimothyStiles/poly#159]
https://github.com/TimothyStiles/poly/blob/0d8b59270b5cd350c2974c28109784c4c36e51be/primers.go#L98

The default concentrations necessary for the `SantaLucia` model seem to hard-coded. Is this by design or something that was just missed in the initial pass ?

**Comment by TimothyStiles** [comment]
By design.

@jecalles can correct me on this by I believe `MeltingTemp `is just calculating assuming sane defaults for non-experts.

If you want to calculate melting temp without defaults `SantaLucia` is also exported.
