### ISSUE TITLE
Rebase commands (ParseRebase, ReadRebase, ExportRebase) are redundant 

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#165]
The rebase commands (ParseRebase, ReadRebase, and ExportRebase) are redundant since they are in the rebase package. We ought to simplify those:

```
rebase.ParseRebase -> rebase.Parse
rebase.ReadRebase -> rebase.Read
rebase.ExportRebase -> rebase.Export
```

**Comment by TimothyStiles** [comment]
> The rebase commands (ParseRebase, ReadRebase, and ExportRebase) are redundant since they are in the rebase package. We ought to simplify those:
> 
> ```
> rebase.ParseRebase -> rebase.Parse
> rebase.ReadRebase -> rebase.Read
> rebase.ExportRebase -> rebase.Export
> ```

Do it.
