### ISSUE TITLE
GbkFlatGz example fails to read feature properly.

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#170]
```
func ExampleReadGbkFlatGz() {
        sequences := ReadGbkFlatGz("data/flatGbk_test.seq.gz")
        //sequences := ReadGbkFlatGz("data/gbbct358.seq.gz")
        var locus []string
        for _, sequence := range sequences {
                locus = append(locus, sequence.Meta.Locus.Name)
        }
        fmt.Println(strings.Join(locus, ", "))
        // Output: AB000100, AB000106
}
```

Parsing this genbank flat file in this example does not get translations of features out.

**Comment by TimothyStiles** [comment]
@Koeng101 by getting translation of features out you mean getting them as specified in the Genbank itself vs. getting the sequence and translating using poly correct?

**Comment by Koeng101** [comment]
> getting them as specified in the Genbank itself

Correct. In Genbank itself is where I want to grab translations from.

**Comment by TimothyStiles** [comment]
Also, before I go off testing as a sanity check are you having issues with the test file or the one you've commented out that you're trying to use in production?

**Comment by Koeng101** [comment]
Commented out.

**Comment by Koeng101** [comment]
(I'm using it as a test for the allbase genbank insertion)

**Comment by TimothyStiles** [comment]
@Koeng101 looking at the test file it's pulling that translation data as intended. How are you accessing it? 

![Screen Shot 2021-06-05 at 11 05 22 AM](https://user-images.githubusercontent.com/7042260/120901145-f0a1f900-c5ed-11eb-9d85-d631a496db28.png)


Also, can you share this different file? I want to make sure I'm using the same thing you are.

**Comment by Koeng101** [comment]
Im an idiot
