### ISSUE TITLE
Migrating to more mature CLI package.

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#172]
**Is your feature request related to a problem? Please describe.**
urface/cli is clunky and missing syntax and docs for simple features.

**Describe the solution you'd like**
[cobra](https://github.com/spf13/cobra#generating-documentation-for-your-command) is used extensively and will likely solve our problems. What we need is.

1. A framework that makes it easy to test commands in a way that doesn't rely on executable. We found a workaround with current library but it's clunky and I actually had to get their maintainers to merge a stale PR that fixed the issue.

2. Lets name be declared in `main.go`. Currently urfave does it through directory name for some reason? Super annoying and new devs get confused thinking that it's source code for the library itself for some reason.

3. Has standard version declaration built in. Urfave doesn't do this.

4. Auto-generate docs. Cobra does this and likely well.

**Describe alternatives you've considered**
We could suffer and try to make PRs to urfave for this functionality.

**Comment by TimothyStiles** [comment]
>     2\. Lets name be declared in `main.go`. Currently urfave does it through directory name for some reason? Super annoying and new devs get confused thinking that it's source code for the library itself for some reason.

Apparently cobra does this too? Woooo. https://github.com/spf13/cobra#generating-documentation-for-your-command

**Comment by rkrishnasanka** [comment]
This looks pretty good actually, allows one to develop a really robust cmdline interface
