### ISSUE TITLE
SplitSet with more features

### ISSUE THREAD

**Issue by isaacguerreir** [TimothyStiles/poly#196]
Part of the process of organism engineering is to make synthesizable parts, when necessary, to construct new sequences and plasmids that add functions to living things. One step that we found out very boring at Friendzymes is to make some parts synthesizable you have to split the original sequence into fragments, either because the original is too big to be synthesize, or because you have problems that could only be resolved by fragment the part. You not only have to make fragments for these parts, but you also have to find overhangs that actually are good and don't generate mismatches.

To create these optimized fragments people use the webtool from NEB called [SplitSet](https://ggtools.neb.com/splitset/run.cgi). They do this manually to produce this output. So @eyesmo asked me if we could make a version where we could automatize new heuristics to this process.

The result is this [repository](https://github.com/Open-Science-Global/SplitSet).

I have some things to resolve, but the main functionalities already work. We also found out that NEB doesn't select the best overhangs, but only finds one that is ok, so in this version of SplitSet we already have better results than the original SplitSet. And yeah, we're using the data they share in the paper and use it to select the best overhangs. (We checked this by using the [Ligase Fidelity Viewer](https://ggtools.neb.com/viewset/run.cgi), another webtool from NEB for this).

I also already integrate this package with IDT API, so we could check if the new fragments are synthesizable running the Complexity Score. If the score it's too high we try other fragmentation options to see if this improves the final selection of fragments.

We also integrate with the finder subpackage to find problematic parts in those sequences and prioritize that in the search of the perfect overhang for a given region we try to put a fragmentation in the middle of the problematic part to minimize even more the complexity score.

My question is more if this is something that will be interesting to have inside poly, or if it's better to have this in a different package. Let me know what you think about this.

**Comment by Koeng101** [comment]
Funny enough, looks like we both made this! Clearly its necessary. https://github.com/Koeng101/pichia_toolkit/tree/main/fragment

**Comment by Koeng101** [comment]
also #84
