### ISSUE TITLE
Ability to generate a attributions file in BibTeX 

### ISSUE THREAD

**Issue by rkrishnasanka** [TimothyStiles/poly#197]
It would be a good feature to have poly generate aa bib file with all the corresponding algorithm references. This will let people easily verify the sequence of algorithms that were used for generating the final outputs. This can be a flag that that the user can optionally enable.

**Describe the solution you'd like**
When the user adds a `--generate-attributions` flag on the commandline, the user will see an `attributions.bib` file at the output that has the references for all the all the algorithm used in the process.

**Describe alternatives you've considered**
Alternatively, it should be a text /markdown file with a table (step | alg | doi)

**Comment by TimothyStiles** [comment]
@rkrishnasanka, I have no idea how this would work? Is this only for command line usage?

Currently we're only supporting conversion and hashing for the command line so this may be a little early.

**Comment by rkrishnasanka** [comment]
Yeah I'm planning to put in a PR for this. I figured I'd start a discussion here so that people might put up the info and extend the command line interface as necessary. I believe the friendzymes people figured out a couple of use cases that seem to make sense to have a command line interface for.

**Comment by TimothyStiles** [comment]
Closing for now. Feel free to open this thread back up.
