### ISSUE TITLE
Biofast comparison

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#21]
Heng Li (inventor of SAM, minimap, etc, basically an absolute madlad that has seriously contributed to bio software space) had this in a blog post:

http://lh3.github.io/2020/05/17/fast-high-level-programming-languages

Looks like Go is about 2x slower than most the other high level languages. It would be great to have a performance test suite of poly vs other REAL bio software (not hypothetical), maybe something that can be automatically run?

**Comment by TimothyStiles** [comment]
@Koeng101 agree that bench marking against other programs would be great but feels like premature optimization for where we are now.

It depends how much you want to benchmark but you could write a benchmarking suite where on every push or pull request to the `prime` branch poly is benchmarked against other packages. The way I'd implement this is by having a separate benchmarking repo that contained benchmark scripts for non poly scripts along with a docker file to build an environment that supports every benchmark language along with a line to build whatever commit of `poly` needs to be tested. When a push or pull request is detected through github actions it would fire a script that deploys the benchmark suite to what is likely a dedicated server where it runs the benchmarks and then generates a report that could be seen via a web dashboard.

At the moment it's overkill but it would be a great incentive to develop IO for speed and I'm interested in seeing it happen eventually.

> Looks like Go is about 2x slower than most the other high level languages

Did you mean other _lower level_ languages? In my opinion C is lower than Rust and Rust is lower than Go in terms of how close to the metal you get but Go is definitely faster than the higher level languages.

Other things to note:

* Heng Li mentions that some of his implementations have annoyed some readers enough that they've contributed their own implementations to be used as a benchmark. The Rust code and Julia code there have been optimized by some people that seemed to not like how their favorite language was being represented. His gzip performance for Golang is a real outlier and completely unexpected, and doesn't seem to be optimized yet.

* Go typically isn't considered as fast as Rust or C but it's much easier to develop in and the tooling is mature plus it's wayyy faster than python. I'm open to possibly making a `poly` implementation in Rust in the future but right now Golang makes more sense overall.
