### ISSUE TITLE
Methylation testing

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#216]
People can get pissy when they don't check methylation when cutting with BsaI:

https://ethanomics.wordpress.com/2013/06/28/bsai-worst-restriction-enzyme-ever/

"One of the sites had a 4 out of 5 bp match to the Dcm recognition site so I wonder if E. coli is not that accurate with Dcm methylation."

We should have a methylation checker function.

**Comment by isaacguerreir** [comment]
I think that instead of making one specific function to find methylation recognition sites, will be better to try to use the #191 finder function.
