### ISSUE TITLE
Pull request template

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#22]
It'd be really cool to have a pull request comment template that prompts people to write about what they're integrating.

If someone could look up how to do this with the .github directory and add one that I could edit and merge it would make a great first contribution!

**Comment by 0x106** [comment]
Hi @TimothyStiles I added a `.github/pull_request_template.md` file (just a stub). There's some docs on doing it [here](https://docs.github.com/en/github/building-a-strong-community/creating-a-pull-request-template-for-your-repository) but it was trivial to add.
