### ISSUE TITLE
Fixing eisen bug in Golden Gate Cloning

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#241]
Run the tests enough and this happens:

![Screen Shot 2022-02-24 at 7 32 14 AM](https://user-images.githubusercontent.com/7042260/155565592-ff0ae1c4-25be-469d-9e44-a9ae71eb0f37.png)

Looks like the cyclic and concurrent nature of our current GoldenGate implementation makes it hard to limit the number of cycles it loops through. @Koeng101 has some ideas to fix this.

**Comment by Koeng101** [comment]
How was this fixed?

**Comment by TimothyStiles** [comment]
@Koeng101 it wasn't but @matiasinsaurralde made a better issue for it #276.
