### ISSUE TITLE
GbkLocationString should be in "Feature" not "Location

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#261]
When developing, it makes more sense for GbkLocationString to be a feature attribute, since location is entirely derived from it.

**Comment by rkrishnasanka** [comment]
I think it might be fine to leave it there; intuitively, if I'd want to find the Gbk source for the location, I'd look at the location object. Otherwise, it would need to be extra work to keep a map of location strings and the corresponding Location objects.

**Comment by carreter** [comment]
Bumping this stale issue - is this still applicable? Do we still want to do it?

**Comment by Koeng101** [comment]
Hmmm, I think @rkrishnasanka is right. I'm going to close for now.
