### ISSUE TITLE
Codon tables should have start codon statistics

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#262]
**Is your feature request related to a problem? Please describe.**
Codon tables should have start codon statistics available for use.

**Comment by rkrishnasanka** [comment]
Where should we be saving this ?

**Comment by Koeng101** [comment]
> What do you mean exactly by "start codon statistics"?

I'd like to know, in a given organism's codon table, how many start codons are alternative start codons (for example in E.coli, how many gtg start codons there are vs ATG start codons

Basically a modification of codonTable from 
```go
// codonTable holds information for a codon table.
type codonTable struct {
    StartCodons []string    `json:"start_codons"`
    StopCodons  []string    `json:"stop_codons"`
    AminoAcids  []AminoAcid `json:"amino_acids"`
}
```

to
```go
// codonTable holds information for a codon table.
type codonTable struct {
    StartCodons []string    `json:"start_codons"`
    StopCodons  []string    `json:"stop_codons"`
    AminoAcids  []AminoAcid `json:"amino_acids"`
   StartCodonStatistics map[string]int
}
```

It's actually not very useful for engineering, it's just something I think is interesting.

**Comment by carreter** [comment]
This should probably be a method in the `Table` interface as well.

**Comment by Koeng101** [comment]
I'd imagine so. As said, this is lower priority because it doesn't matter that much when it comes to building things, but I think it is interesting and shows something about the organisms.
