### ISSUE TITLE
Suggestion: make the project part of Hacktoberfest

### ISSUE THREAD

**Issue by matiasinsaurralde** [TimothyStiles/poly#277]
[Hacktoberfest](https://hacktoberfest.com/) is running this month and I think it might be useful to gain exposure.

It seems that you only need to add `hacktoberfest` to the repo's topics in order to enable this.

Screenshot from my Hacktoberfest account -they automatically follow al PRs I make, even in non-participating repos-:
<img width="895" alt="Captura de Pantalla 2022-10-15 a la(s) 19 07 32" src="https://user-images.githubusercontent.com/20110/196009378-cd2d75ac-fa1c-40dd-a052-08e81174877c.png">

**Comment by TimothyStiles** [comment]
Just added hacktoberfest to the repo's topics!
