### ISSUE TITLE
rebase can contain multiple references

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#278]
https://github.com/TimothyStiles/poly/blob/f2dcf099fea761c9d00d7fadbe50e3d92652e71c/io/rebase/rebase.go#L242-L246

Current parser version only parses a single reference. Enzymes like BsaI have multiple references.

**Comment by rkrishnasanka** [comment]
Yeah even the test is off, I checked the rebase test file, it looks like it has enzymes with multiple references and it still clears it

**Comment by palmerito0** [comment]
As far as I can tell none of the tests actually check the contents of the resulting `enzymeMap` after parsing, just the fact that parsing proceeds without error.
