### ISSUE TITLE
Fail to parse Saccharomyces cerevisiae S288C chromosome I

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#310]
2023/05/29 09:52:20 Failed to parse i.gb with err: Failed in parsing reference above line 41. Got error: ReferenceKey not in [AUTHORS, TITLE, JOURNAL, PUBMED, REMARK]. Got:
CONSRTM

https://www.ncbi.nlm.nih.gov/nuccore/NC_001133.9

**Comment by TimothyStiles** [comment]
is CONSRTM a standard reference key @Koeng101?

**Comment by Koeng101** [comment]
I dunno. It's in refseq though, on possibly one of the most used genome.

**Comment by carreter** [comment]
I think #320 fixed this. Will double check right now!

**Comment by Koeng101** [comment]
Yes fixed! Ima close this.
