### ISSUE TITLE
`CODE_OF_CONDUCT.md` missing contact under Enforcement section

### ISSUE THREAD

**Issue by carreter** [TimothyStiles/poly#345]
Currently just says [INSERT CONTACT METHOD]. Should we set up a mailing list or some way of contact all the collaborators on the repo? We could also just list @TimothyStiles 's email.

https://github.com/TimothyStiles/poly/blob/10b8f398c4272700dd27a177af244d6b531d2582/CODE_OF_CONDUCT.md?plain=1#L60-L68

**Comment by TimothyStiles** [comment]
I think there may be some new GitHub feature for this + security related issues. Checking now.

**Comment by TimothyStiles** [comment]
The only thing that seems to be close is using github's security advisory feature which is close to what we need (only collaborators can see, easy to use from GitHub) but has required form fields for security related stuff.

How easy would it be to setup and admin a mailing list?

**Comment by carreter** [comment]
Would be very easy to do with Google Groups.

**Comment by Koeng101** [comment]
Or https://lists.sr.ht if you like more open-source style stuff

**Comment by carreter** [comment]
> Or https://lists.sr.ht/ if you like more open-source style stuff

Seems like that requires the project be hosted on sourcehut, which is paid?

**Comment by Koeng101** [comment]
> > Or https://lists.sr.ht/ if you like more open-source style stuff
> 
> Seems like that requires the project be hosted on sourcehut, which is paid?

I do pay for sourcehut and I don't think it requires the project to be hosted on sourcehut. I mostly just like their philosophy on open source tools, which unfortunately "everyone uses GitHub" overrides for a lot of stuff

**Comment by carreter** [comment]
Gotcha. No preference between the two on my end - just let me know which one to use and I will set it up!

**Comment by carreter** [comment]
I've created poly-collaborators@googlegroups.com. PR listing this as the contact to follow...
