### ISSUE TITLE
MASH template matching

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#356]
So, the idea is that I have many templates and many reads. Many of those templates are similar (perhaps only a 4bp difference in 5000bp). I want a method that will be able to tell me the most likely template that those reads belong to - assuming that all the different sequencing reads go to the same template, but are just a little bit noisy (1/50 random mutation or so).

This would greatly help my sequencing pipelines, and I imagine would help other sequencing pipelines.

**Comment by TimothyStiles** [comment]
There have been demonstrations of template matching using MASH but I'm not so sure if there's anything about extremely small variance between sequences. I'm open to maybe supporting a general template matching function as a demo to start but don't know if I want to maintain that in a stable release yet @Koeng101.
