### ISSUE TITLE
This project should have a `CHANGELOG.md`

### ISSUE THREAD

**Issue by carreter** [TimothyStiles/poly#369]
**Is your feature request related to a problem? Please describe.**
We currently do not have a way of keeping track of what is changing from release to release. This will become especially important once we release `v1.0`, as clients will start depending on functionality being stable and breaking changes to our API should be well documented.

**Describe the solution you'd like**
https://keepachangelog.com/en/1.1.0/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TimothyStiles** [comment]
Closest thing that we have to a change log right now is the on that's
generated for each release.

Usually I make a big BREAKING CHANGES header for what's going on but
something a little more refined could be good.
