### ISSUE TITLE
Concurrent mashing

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#380]
In my sequencing pipeline, currently the slowest part is the sequence mashing, running on one core. It would be nice to be able to do this concurrently, built in: because the primary use case is probably going to be mashing a LOT of sequences.

What I am specifically looking for:

1. Many reads input, grouped together. Each read group targets a certain template, but we don't know which one.
2. Many templates input
3. The most likely template for the reads as an output

**Comment by TimothyStiles** [comment]
@Koeng101 that implementation is super naive and I'd recommend it be tuned up a little for performance before it being merged into main with things like what you're suggesting built on top of it. Check out details on #344.
