### ISSUE TITLE
Genbank import and export from JSON should include feature sequences

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#388]
Right now, it is a REAL pain to read location strings and properly parse. This makes it rather difficult to actually use JSON upstream or downstream from Golang. I think upon export, Genbank file features sequence should be exported.

**Comment by TimothyStiles** [comment]
@Koeng101 is this a thing in the #339 refactor? I'm thinking maybe we should just use parameter structs for parsers and just have it be a flag when parsing?

**Comment by Koeng101** [comment]
yes, it is. 

> we should just use parameter structs for parsers and just have it be a flag when parsing?

I'm a bit confused why, for this specifically. The data doesn't change at all when parsing, so why would we pass in a parameter struct into a parser containing information about the output JSON encoding for the downstream parsed structs?
