### ISSUE TITLE
Simplifying codon table interface

### ISSUE THREAD

**Issue by cachemoi** [TimothyStiles/poly#392]
this is an issue suggested as a follow up to this [PR](https://github.com/TimothyStiles/poly/pull/350), we have a [table](https://github.com/TimothyStiles/poly/pull/350/files#diff-874dd545acc993503bc81ceab036740766e4192dbcb01dfdef9e1c91ec8400efR85) interface which exposes a potentially superflous `GetWeightedAminoAcids` function. The function is used to get a weighted amino acid sequence in the `fix` DNA optimisation package. 

The `fix` package seems to be [updating the weights with more data](https://github.com/TimothyStiles/poly/blob/main/synthesis/fix/synthesis.go#L241), we should consider putting all the functions which updates those amino acid weights in the same struct for a less leaky abstraction.

**Comment by Koeng101** [comment]
> The fix package seems to be [updating the weights with more data](https://github.com/TimothyStiles/poly/blob/main/synthesis/fix/synthesis.go#L241), we should consider putting all the functions which updates those amino acid weights in the same struct for a less leaky abstraction

Could you be more specific on the line? I don't recall it updating the weight table with more data, just getting out which new codon it should use based on the data, then applies biases.

Agreed it should be updated though.

**Comment by cachemoi** [comment]
I assumed it was updating the weights with some other heuristics but after reading more carefully I see it's not, I thought it would be a duplicate of the codon picking mechanism in [optimize](https://github.com/TimothyStiles/poly/blob/main/synthesis/codon/codon.go#L176C3-L176C9)

If I understand well the package is using the weighted AAs to get the highest weighted codon in a set of potential codon replacements gotten with other methods (gc bias ect...) [here](https://github.com/TimothyStiles/poly/blob/main/synthesis/fix/synthesis.go#L353C5-L356).

I don't really see a straightforward way to get rid of this in a way that make things noticably better since it's using the `fix.Change` [struct](https://github.com/TimothyStiles/poly/blob/main/synthesis/fix/synthesis.go#L49) so I think it's best to leave things as is 👍
