### ISSUE TITLE
HELLO MY WORD 👋👋

### ISSUE THREAD

**Issue by Thailandvango** [TimothyStiles/poly#405]
## Describe the desired feature/enhancement
*A clear and concise description of what you want to happen.*

### Is your feature request related to a problem?
*A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]*

### Describe the solution you'd like
*A clear and concise description of what you want to happen.*

### Describe alternatives you've considered (optional)
*A clear and concise description of any alternative solutions or features you've considered.*

## Additional context
*Add any other context or screenshots about the feature request here.*

**Comment by carreter** [comment]
Please do not post empty issues here. Feel free to make a thread in the discussions page if you want to introduce yourself!
