### ISSUE TITLE
Optimizing sequences

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#41]
Before a sequence is synthesized it should be optimized in at least 3 ways that I can think of.

* Codon optimization for a target organism
* Non-repetitive parts optimization for a target organism
* Synthesis optimization (optimizing sequence for probability of synthesis success)

Each optimization would have its own function but it'd be great to eventually have a function that performs a suite of pre-synthesis optimizations and checks.

@Koeng101 has already written a little about [codon optimization](https://github.com/TimothyStiles/poly/pull/11) and [synthesis optimization](https://github.com/TimothyStiles/poly/issues/12) but we've yet to start working on non-repetitive parts optimization. **Are there any other pre-synthesis optimizations that we should be considering?**

**Comment by Koeng101** [comment]
> Non-repetitive parts optimization for a target organism

The best way to do this is to take the target organism + your sequence of interest and building a suffix array / LCP array for them together. Then, you just look for large LCPs.
