### ISSUE TITLE
Adding a documentation site.

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#5]
**Is your feature request related to a problem? Please describe.**

Poly should have a nice documentation site. 

**Describe the solution you'd like**

An out of the box solution that is pretty and has examples to complement go docs. 
https://squidfunk.github.io/mkdocs-material/ comes to mind.

**Describe alternatives you've considered**

I'm not sure what alternatives there are at the moment but I made this thread to attract ideas and document solutions that I find.

**Comment by Koeng101** [comment]
I like using mdBook for things like this, which is very simple https://rust-lang.github.io/mdBook/index.html. Would recommend, though mkdocs looks like pretty much the same idea.

**Comment by Koeng101** [comment]
@TimothyStiles Have you thought more about a solution here? We should try to build the docs site while building the application so docs stay up to date.

**Comment by TimothyStiles** [comment]
@Koeng101 [docusaurus](https://docusaurus.io) looks similar too. Right now I'm trying to think of the cleanest way to integrate everything.

**Comment by Koeng101** [comment]
Doc website here - https://timothystiles.github.io/polydocs/
Doc github here - https://github.com/TimothyStiles/polydocs

**Comment by TimothyStiles** [comment]
I'm super excited to announce that `poly`'s doc site has been integrated with github actions and now works as a continuous deployment. All that's needed to update the blog or docs is to make changes to the prime branch in the `docs` or `blog` directory and changes should be made on merge. Check out the new site!

https://timothystiles.github.io/poly/
