### ISSUE TITLE
Writing SBOL3 IO

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#52]
**Is your feature request related to a problem? Please describe.**

People keep asking for SBOL3 IO so I thought there should be an issue for it.

**Describe the solution you'd like**

The SBOL3 parser should implement four functions `ReadSBOL, ParseSBO, BuildSBOL, WriteSBOL.

* `ReadSBOL` pretty much just does file io and passes a file string to `ParseSBOL`.

* `ParseSBOL` picks apart the sbol file string and appropriately fills an AnnotatedSequence instance with it.

* `BuildSBOL` takes an `AnnotatedSequence` object and uses it to build a string that can be passed to `WriteSBOL`.

* ` WriteSBOL` writes an SBOL string to file.

Each function should be tested. The easiest way is to read, and parse an SBOL into a `Sequence` then build a string with it and write it out then compare the input with the output. If they're the same then you've done it!

**Comment by Koeng101** [comment]
SBOL3 is probably where it is worth going to. SBOL2 will be going away at some point, might as well focus on the future!
