### ISSUE TITLE
CRISPR Gopher mascot

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#62]
Lots of Go related projects adopt a dressed up Go Gopher as a mascot and we should too!

[Examples](https://github.com/ashleymcnamara/gophers)

- Gopher using DNA as jump rope

- Gopher cutting DNA with scissors

- Gopher duct taping DNA back together

- Gopher inspecting peptide chains emerging from ribosomes with a little monocle

I'm not much an artist myself but if anyone could make a gopher fit for a mascot I'd be grateful. Any ideas on what their outfit should be?

**Comment by Koeng101** [comment]
+1 to the Gopher clumsily duct taping DNA together, though I'm down for any of the others too!
