### ISSUE TITLE
Start and End of features not properly parsed

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#7]
**Describe the bug**
JSON object representation of Genbank features don't have proper `Start` and `End` values. The `Location` field, as far as I know, is slightly different. Start and end should either have simple integer values, or be redundant with `Location`

**To Reproduce**
`cat bsub.gbk | poly c -i gbk -o json > bsub.json`

**Expected behavior**
The `Start` and `End` fields in the JSON output should match the Genbank outputs.

**Screenshots**

**Desktop (please complete the following information):**
 - Arch linux, compiled with go.

**Additional context**

**Comment by TimothyStiles** [comment]
This is currently being resolved in PR #13 .

**Comment by TimothyStiles** [comment]
This issue has been fixed with merged PR #13.
