### ISSUE TITLE
Update Seqhash algorithm

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#74]
**Is your feature request related to a problem? Please describe.**
Update the seqhash algorithm to give versioned output. For example, pUC19 would be `v1_DCD_4b0616d1b3fc632e42d78521deb38b44fba95cca9fde159e01cd567fa996ceb9`, with the DCD standing for "DNA-Circular-Double stranded".

**Describe the solution you'd like**
https://git.sr.ht/~koeng/python-seqhash/tree/master/seqhash/__init__.py similar output to the reference code.

**Describe alternatives you've considered**

**Additional context**

**Comment by TimothyStiles** [comment]
This has been added as of Pr #82. Closing.
