### ISSUE TITLE
TestTranslationString fails randomly during PRs

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#77]
**Describe the bug**
`TestTranslationString` oftentimes (not always) fails during the Github ci test suite. This *only* happens with mac OSX. I have no idea why

**To Reproduce**
1. Make new Pull request
2. Watch this one test function fail

**Expected behavior**
Mac OSX failures should probably be the same as ubuntu failures, and if it is going to fail, just fail every time.

**Additional context**
I see that that function is using some stdin stuff - maybe mac doesn't do that right? idk

**Comment by TimothyStiles** [comment]
At this point I'm apt to believe that this is a problem with github actions as I have run into similar problems with running ubuntu tests with other PRs.

I'm not sure what the best solution is here other than changing CI/CD tool to something like circle, or just refreshing gh actions every time a test fails.

Super annoying.

**Comment by Koeng101** [comment]
I could self host a CI/CD on the Poly codonOptimizer namespace if needed

**Comment by TimothyStiles** [comment]
@Koeng101 has this been resolved such that I can close this issue?
