### ISSUE TITLE
Why is there Linear and Circular bools on Locus struct?

### ISSUE THREAD

**Issue by Koeng101** [TimothyStiles/poly#89]
**Describe the bug**
In io.go at line 80 + 81, there is a `Circular` and `Linear` field, both as booleans. Couldn't you just have one? (Since if Circular is false, linear is true, and vice versa, by definition). 

Is this here simply to accommodate the ambiguous case? 

**To Reproduce**
go to io.go

**Expected behavior**
A single field

**Screenshots**

**Additional context**

**Comment by Koeng101** [comment]
@TimothyStiles I can fix the cloning stuff if I have an answer to this

**Comment by TimothyStiles** [comment]
@Koeng101 did we already solve this? Should be fixed with #227.

**Comment by Koeng101** [comment]
Think so. Let's close.

**Comment by Koeng101** [comment]
https://github.com/TimothyStiles/poly/blob/beacf5d83d54f588c154a634e9f222b27349291c/io/genbank/genbank.go#L97-L98

Heyyyyyy
