### ISSUE TITLE
easy_dna functionality port.

### ISSUE THREAD

**Issue by TimothyStiles** [TimothyStiles/poly#91]
I had a great call the other month with the developer of [easy_dna](https://edinburgh-genome-foundry.github.io/easy_dna) and he suggested that even though it isn't by far his most popular library it is his most useful and that poly should have similar functionality. Below is a list of functions that I will accept PRs for if ported. See above link for documentation and links to original source code. Please make sure they are well tested!

all_iupac_variants
~~anonymized_record~~
~~copy_and_paste_segment~~
~~cut_and_paste_segment~~
dna_pattern_to_regexpr
list_common_enzymes
random_dna_sequence
random_protein_sequence
~~replace_segment~~
~~reverse_segment~~
~~swap_segments~~

Thanks,
Tim

P.S some clarifying info that Davian asked for.

Most functions will likely fit into the scope of either sequence.go or transformations.go and their associated test files. If you feel like a function doesn't fit within the scope of either you can make a utils.go and utils_test.go in the projects main directory to include with your pull request.

Most functions can be written as standalone string functions and then be wrapped by a method to use with poly's main sequence struct. That's as complex as integration with the main library will have to be in most cases.

**Comment by rkrishnasanka** [comment]
@TimothyStiles this matches the `sequence-level` tools I was talking about. I can imagine another layer of abstraction that can utilize these functions for `part-level` tools that can take advantage of these functions. 

If your roadmap includes the part level operations and being able to use both MoClo and Biobrick parts for different types of assembly. I think iGEM students will be able to use poly for the day-to-day.

**Comment by tijeco** [comment]
I'd like to work on some of these! I can raise an issue for each function I decide to work on so that I can be assigned to it, if that would help out with tracking things.

**Comment by dexho** [comment]
Jeff, we'll do that as well

**Comment by aleyshachen** [comment]
I can work on dna_pattern_to_regexpr!

**Comment by maplemuffet** [comment]
I'll work on random_dna_sequence :)

**Comment by tijeco** [comment]
Perfect! I'll start with all_iupac_variants. I'll raise an issue this evening.

**Comment by patrickjyoung** [comment]
I can work on list_common_enzymes!

**Comment by TimothyStiles** [comment]
Since all functions have been claimed by someone or another I'm going to close this issue. Please open a pull request and cite this issue to merge.
