### ISSUE TITLE
all_iupac_variants port from easy_dna

### ISSUE THREAD

**Issue by tijeco** [TimothyStiles/poly#92]
From [easy_dna](https://edinburgh-genome-foundry.github.io/easy_dna/). Return all unambiguous possible versions of the given sequence.

```python
>>> all_iupac_variants('ATN')
>>> ['ATA', 'ATC', 'ATG', 'ATT'] 
```

Will be using the ambiguity codes from [here](https://genome.ucsc.edu/goldenPath/help/iupac.html).

**Comment by TimothyStiles** [comment]
@tijeco any recent progress?

**Comment by tijeco** [comment]
@TimothyStiles thanks for checking in! I have working on this on my calendar for tomorrow!

**Comment by tijeco** [comment]
I got a chance to work on this today!

I thought I had a solution until I did some tests.... Will keep at it though! 

The original implementation had a quippy one liner with itertools, so I'm thinking some sort of recursion might be needed.

It's a fun problem!
